### ISSUE TITLE
Fine-tuning LLaVA-7B-ov with multiple tokens causes deadlock issues.

### ISSUE THREAD

**Issue by yyxisgreat** [zjysteven/lmms-finetune#79]
I fine-tuned LLaVA-7B-ov using two A100 GPUs, running with a batch size of 1, grad acc set to 2, and a max length of 8192. I frequently encounter NCCL deadlocks after running for a while. Could you advise on how to resolve this?

The following is the error message:

[Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3314, OpType=_ALLGATHER_BASE,
 NumelIn=6424320, NumelOut=12848640, Timeout(ms)=1800000) ran for 1800027 milliseconds before timing out.

**Comment by lavinal712** [comment]
This information is a bit limited for me. Could you please provide the full error message and details about your Python environment?

**Comment by yyxisgreat** [comment]
Thank you very much for your reply. I've resolved the issue—it was caused by installing a too-high version of torch (2.8.0), which was incompatible with my GPU driver. I suggest limiting the torch version in requirement.txt, as this might prevent future users from encountering similar problems. Thank you for your excellent open-source work!
